version: "3.8"

services:
  app:
    image: task-manager:${TAG}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-manager
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    networks:
      - task-manager
  db:
    image: postgres:17.2
    container_name: postgres-db
    restart: unless-stopped
    user: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./app_schema.sql:/docker-entrypoint-initdb.d/app_schema.sql
    networks:
      - task-manager
networks:
  task-manager:



