# version: "3.9"

services:
  app:
    image: task-manager:${TAG}
    user: ${UID}:${GID}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-manager
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
    depends_on:
      - db
    networks:
      - task-manager
  db:
    image: postgres:17.2
    command: -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
    container_name: postgres-db
    restart: unless-stopped
    user: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./app_schema.sql:/docker-entrypoint-initdb.d/app_schema.sql
      - ./certs/server.crt:/var/lib/postgresql/server.crt
      - ./certs/server.key:/var/lib/postgresql/server.key
      - ./certs/root.crt:/var/lib/postgresql/root.crt
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    networks:
      - task-manager
networks:
  task-manager: